apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lemon-korean

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-statefulset.yaml
  - mongodb-statefulset.yaml
  - redis-deployment.yaml
  - minio-statefulset.yaml
  - rabbitmq-deployment.yaml
  - auth-service-deployment.yaml
  - content-service-deployment.yaml
  - progress-service-deployment.yaml
  - media-service-deployment.yaml
  - analytics-service-deployment.yaml
  - admin-service-deployment.yaml
  - nginx-ingress.yaml

commonLabels:
  app.kubernetes.io/name: lemon-korean
  app.kubernetes.io/managed-by: kustomize
